-- Migration: create_reportes_generados
-- Creates the reportes_generados table with RLS enabled and default policies.

create table if not exists public.reportes_generados (
  id            uuid primary key default gen_random_uuid(),
  area          text        not null,
  generado_por  uuid        not null references auth.users (id) on delete cascade,
  fecha_inicio  date        not null,
  fecha_fin     date        not null,
  csv_url       text,
  created_at    timestamptz not null default now()
);

comment on table public.reportes_generados is
  'Stores metadata for every CSV report generated by area supervisors';

-- Enable Row Level Security
alter table public.reportes_generados enable row level security;

-- Policy: each authenticated user can read only their own reports
create policy "Users can view their own reports"
  on public.reportes_generados
  for select
  using (auth.uid() = generado_por);

-- Policy: each authenticated user can insert their own reports
create policy "Users can create their own reports"
  on public.reportes_generados
  for insert
  with check (auth.uid() = generado_por);

-- Policy: admins (service_role) can do everything
drop policy if exists "Service role has full access" on public.reportes_generados;
create policy "Service role has full access"
  on public.reportes_generados
  for all
  using (auth.role() = 'service_role');
